(() => {
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const header = $('.site-header');
  const onScroll = () => header?.classList.toggle('scrolled', scrollY > 20);
  onScroll(); addEventListener('scroll', onScroll, { passive:true });
  const io = new IntersectionObserver((entries) => { entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); io.unobserve(e.target); } }); }, { threshold:.12 });
  $$('.reveal').forEach(el => io.observe(el));
  const typed = $('#typedText'); const words = ['technology', 'finance', 'storytelling', 'systems', 'design']; let wi=0, ci=0, deleting=false;
  function typeLoop(){ if(!typed) return; const word=words[wi]; if(!deleting){ci++; typed.textContent=word.slice(0,ci); if(ci===word.length){deleting=true; return setTimeout(typeLoop,1100);}} else {ci--; typed.textContent=word.slice(0,ci); if(ci===0){deleting=false; wi=(wi+1)%words.length;}} setTimeout(typeLoop,deleting?42:70); }
  setTimeout(typeLoop,700);
  const glow = $('#cursorGlow'); addEventListener('pointermove', e => { if(glow){ glow.style.left=e.clientX+'px'; glow.style.top=e.clientY+'px'; } }, { passive:true });
  const canvas = $('#networkCanvas');
  if(canvas && !matchMedia('(prefers-reduced-motion: reduce)').matches){ const ctx=canvas.getContext('2d'); let w,h,dpr,nodes=[]; function resize(){ dpr=Math.min(devicePixelRatio||1,2); w=innerWidth; h=innerHeight; canvas.width=w*dpr; canvas.height=h*dpr; canvas.style.width=w+'px'; canvas.style.height=h+'px'; ctx.setTransform(dpr,0,0,dpr,0,0); const count=Math.min(46,Math.max(22,Math.floor(w/35))); nodes=Array.from({length:count},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18,r:Math.random()*1.1+.45})); }
    function draw(){ ctx.clearRect(0,0,w,h); for(const n of nodes){n.x+=n.vx;n.y+=n.vy;if(n.x<-20)n.x=w+20;if(n.x>w+20)n.x=-20;if(n.y<-20)n.y=h+20;if(n.y>h+20)n.y=-20;ctx.fillStyle='rgba(118,219,255,.25)';ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill();} for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j],dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy);if(d<135){ctx.strokeStyle=`rgba(116,168,255,${(1-d/135)*.055})`;ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}} requestAnimationFrame(draw); }
    resize(); addEventListener('resize',resize); draw(); }
  $$('.research-tab').forEach(btn => btn.addEventListener('click', () => { $$('.research-tab').forEach(x=>x.classList.remove('active')); $$('.research-panel').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); $(`[data-panel="${btn.dataset.tab}"]`)?.classList.add('active'); }));
  $$('[data-tilt]').forEach(card => { card.addEventListener('pointermove', e => { if(matchMedia('(max-width: 800px)').matches) return; const r=card.getBoundingClientRect(), x=(e.clientX-r.left)/r.width-.5, y=(e.clientY-r.top)/r.height-.5; card.style.transform=`perspective(900px) rotateX(${(-y*2.2).toFixed(2)}deg) rotateY(${(x*2.8).toFixed(2)}deg) translateY(-2px)`; }); card.addEventListener('pointerleave',()=>card.style.transform=''); });
  const counterIO = new IntersectionObserver(entries => entries.forEach(e => { if(!e.isIntersecting) return; const el=e.target, end=Number(el.dataset.counter); const prefix=el.dataset.prefix||'', suffix=el.dataset.suffix||''; const start=performance.now(), dur=1000; function tick(t){const p=Math.min(1,(t-start)/dur), ease=1-Math.pow(1-p,3), value=Math.round(end*ease); el.textContent=prefix+value.toLocaleString()+suffix; if(p<1)requestAnimationFrame(tick);} requestAnimationFrame(tick); counterIO.unobserve(el); }),{threshold:.65}); $$('[data-counter]').forEach(x=>counterIO.observe(x));
  const dialog=$('#commandDialog'), open=$('#openCommand'), input=$('#commandInput'), list=$('#commandList'); function openCmd(){ if(!dialog?.open){dialog.showModal(); setTimeout(()=>input?.focus(),20);} } function closeCmd(){ if(dialog?.open) dialog.close(); }
  open?.addEventListener('click',openCmd); addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCmd();} if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();openCmd();}}); input?.addEventListener('input',()=>{const q=input.value.toLowerCase().trim(); $$('a',list).forEach(a=>a.hidden=q&&!a.dataset.command.includes(q));}); $$('a',list).forEach(a=>a.addEventListener('click',closeCmd)); dialog?.addEventListener('click',e=>{if(e.target===dialog)closeCmd();});
})();